home:
  uri: /
  controller: IndexController
  action: showHome
  parameters: [ ]
contact:
  uri: /contact
  controller: IndexController
  action: showContact
  parameters: [ ]
singlePost:
  uri: /blog/([a-zA-Z0-9-]+)
  controller: BlogController
  action: showPost
  parameters: ["id_post"]