home:
  uri:              /
  controller:       IndexController
  action:           showHome
  parameters:       [ ]
contact:
  uri:              /contact
  controller:       IndexController
  action:           showContact
  parameters:       [ ]
blogPage:
  uri:              /blog/([0-9-]+)/
  controller:       BlogController
  action:           showBlog
  parameters:       ["page"]
singlePost:
  uri:              /blog/([a-zA-Z0-9-]+)
  controller:       BlogController
  action:           showPost
  parameters:       ["slug"]
administration:
   uri:             /admin/
   controller:      AdminController
   action:          showAdmin
   parameters:      [ ]
listComments:
   uri:              /admin/blog/commentaires/
   controller:       AdminController
   action:           showCommentList
   parameters:       [ ]
showEditInformations:
   uri:              /admin/informations/
   controller:       AdminController
   action:           showEditInformations
   parameters:       [ ]
editInformations:
   uri:              /admin/informations/changer_informations/
   controller:       AdminController
   action:           editInformations
   parameters:       [ ]
editCV:
   uri:              /admin/informations/changer_cv/
   controller:       AdminController
   action:           editCV
   parameters:       [ ]
editProfileImg:
   uri:              /admin/informations/changer_image_profil/
   controller:       AdminController
   action:           editProfileImg
   parameters:       [ ]
showSocialList:
   uri:              /admin/reseaux/
   controller:       AdminController
   action:           showSocialList
   parameters:       [ ]
addSocial:
   uri:              /admin/reseaux/ajouter
   controller:       AdminController
   action:           addSocial
   parameters:       [ ]
deleteSocial:
   uri:              /admin/reseaux/([a-zA-Z0-9-]+)/supprimer/
   controller:       AdminController
   action:           deleteSocial
   parameters:       ["id"]
editSocial:
   uri:              /admin/reseaux/([a-zA-Z0-9-]+)/edit/
   controller:       AdminController
   action:           editSocial
   parameters:       ["id"]
listPost:
  uri:              /admin/blog/
  controller:       AdminController
  action:           showPostList
  parameters:       [ ]
addPost:
  uri:              /admin/blog/ajouter/
  controller:       AdminController
  action:           addPost
  parameters:       [ ]
addComment:
  uri:              /blog/([a-zA-Z0-9-]+)/commentaire/ajouter/
  controller:       CommentController
  action:           addComment
  parameters:       ["id"]
editPost:
  uri:              /admin/blog/([a-zA-Z0-9-]+)/modifier/
  controller:       AdminController
  action:           editPost
  parameters:       ["slug"]
deletePost:
  uri:              /admin/blog/([a-zA-Z0-9-]+)/supprimer/
  controller:       AdminController
  action:           deletePost
  parameters:       ["slug"]
login:
  uri:              /connexion
  controller:       AccountController
  action:           login
  parameters:       [ ]
disconnect:
  uri:              /deconnexion
  controller:       AccountController
  action:           disconnect
  parameters:       [ ]
register:
  uri:              /inscription
  controller:       AccountController
  action:           register
  parameters:       [ ]
toggleCommentStatus:
   uri:             /admin/commentaire/([a-zA-Z0-9-]+)/changer-statut/
   controller:      CommentController
   action:          toggleCommentStatus
   parameters:      ["id"]
error:
   uri:              /erreur
   controller:       IndexController
   action:           showError
   parameters:       [ ]
errorAdmin:
   uri:              /admin/erreur
   controller:       IndexController
   action:           showError
   parameters:       [ ]
