home:
  uri:              /
  controller:       IndexController
  action:           showHome
  parameters:       [ ]
contact:
  uri:              /contact
  controller:       IndexController
  action:           showContact
  parameters:       [ ]
portfolio:
  uri:              /portfolio
  controller:       IndexController
  action:           showPortfolio
  parameters:       [ ]
blogPage:
  uri:              /blog/([0-9-]+)/
  controller:       BlogController
  action:           showBlog
  parameters:       ["page"]
singlePost:
  uri:              /blog/([a-zA-Z0-9-]+)
  controller:       BlogController
  action:           showPost
  parameters:       ["slug"]
administration:
   uri:             /admin/
   controller:      AdminController
   action:          showAdmin
   parameters:      [ ]
listComments:
   uri:              /admin/blog/commentaires/
   controller:       AdminController
   action:           showCommentList
   parameters:       [ ]
editPortfolio:
   uri:              /admin/portfolio/
   controller:       AdminController
   action:           editPortfolio
   parameters:       [ ]
editSocials:
   uri:              /admin/reseaux/
   controller:       AdminController
   action:           editSocials
   parameters:       [ ]
listPost:
  uri:              /admin/blog/
  controller:       AdminController
  action:           showPostList
  parameters:       [ ]
addPost:
  uri:              /admin/blog/ajouter/
  controller:       AdminController
  action:           addPost
  parameters:       [ ]
editPost:
  uri:              /admin/blog/([a-zA-Z0-9-]+)/modifier/
  controller:       AdminController
  action:           editPost
  parameters:       ["slug"]
deletePost:
  uri:              /admin/blog/([a-zA-Z0-9-]+)/supprimer/
  controller:       AdminController
  action:           deletePost
  parameters:       ["slug"]
login:
  uri:              /connexion
  controller:       AccountController
  action:           login
  parameters:       [ ]
disconnect:
  uri:              /deconnexion
  controller:       AccountController
  action:           disconnect
  parameters:       [ ]
register:
  uri:              /inscription
  controller:       AccountController
  action:           register
  parameters:       [ ]
toggleCommentStatus:
   uri:             /admin/commentaire/([a-zA-Z0-9-]+)/changer-statut/
   controller:      CommentController
   action:          toggleCommentStatus
   parameters:      ["id"]
error:
 uri:              /erreur
 controller:       IndexController
 action:           showError
 parameters:       [ ]
errorAdmin:
 uri:              /admin/erreur
 controller:       IndexController
 action:           showError
 parameters:       [ ]
